### ISSUE TITLE
Unfairness in ContinuousGenAlgSolver's crossover operation

### ISSUE THREAD

**Issue by igorcadelima** [diogomatoschaves/geneal#12]
The current strategy used in the ContinuousGenAlgSolver's create_strategy method is biased toward the direction of the parent `pa[i]` for both offsprings, as named in this line:
https://github.com/diogomatoschaves/geneal/blob/86279e9ad3891ff2fa6d633dbcb437184f8c9761/geneal/genetic_algorithms/genetic_algorithm_base.py#L162

The following illustration demonstrates what is currently happening, where the squiggly blue line represents the selection interval for the first offspring and the green represents the selection interval for the second offspring:

![image](https://user-images.githubusercontent.com/3990564/192154200-372edcc1-6a7a-4869-9a98-43ea2b95ecf9.png)

Looking at the code, it seems that the method `create_offspring` attempted to perform a blend crossover at a given gene. If so, it is important to remind this approach consists of choosing a constant beta in the [0,1] interval, although it is commonly set to 0.5. Then, we ensure `P1[i] <= P2[i]` so the expression of the gene `i` under crossover is randomly selected from the following interval:

$$ [P1\[i\] - \beta(P2\[i\] - P1\[i\]), P2\[i\] + \beta(P2\[i\] - P1\[i\]) $$

Here is an illustration of how the selection interval for the gene expression changes given different values of beta:
![image](https://user-images.githubusercontent.com/3990564/192155480-8c4eb523-d58e-4858-9fa4-a7a39c9091b6.png)

Therefore, currently, the only scenario which follows the blend strategy correctly is when `P1[i] == P2[i]`, all the rest is biased as shown above.

**Comment by diogomatoschaves** [comment]
Hi Igor,

This is the crossover method that was attempted at being implemented, which was taken from "Practical Genetic Algorithms" by R.L. Haupt and S.L. Haupt. According to this method, a random Beta should be selected. 
<img width="180" alt="Screenshot 2022-09-26 at 19 18 11" src="https://user-images.githubusercontent.com/11161499/192340516-53e57529-da8c-4f39-864a-f06491df055e.png">
However, looking again at the code made me see some inconsistencies in the code. The Beta should be the same for both new offsprings (whereas the current method chooses a random Beta for every new offspring), and there is also a problem with the sign of Beta, which should always be negative, to make:
<img width="258" alt="Screenshot 2022-09-26 at 19 35 27" src="https://user-images.githubusercontent.com/11161499/192343303-7fd4c9a9-d1ba-4ad2-a748-26adbbf2399b.png">

I'll make a pull request with the changes and send you a link for you to see it.
