### ISSUE TITLE
Mutation not applying to fittest individual

### ISSUE THREAD

**Issue by igorcadelima** [diogomatoschaves/geneal#13]
The base method `mutate_population` never picks the first individual for mutation. As a result, since this method is always called given a population sorted by the fitness value in descending order, for cases where `selection_rate < 1.0`, there's elitism of size 1.

https://github.com/diogomatoschaves/geneal/blob/86279e9ad3891ff2fa6d633dbcb437184f8c9761/geneal/genetic_algorithms/genetic_algorithm_base.py#L451-L453

**Comment by diogomatoschaves** [comment]
Hi Igor, thanks for your input! The behaviour of always keeping the fittest individual intact (no mutations) is intended, as that ensures that we do not lose its "genetic material" and get worse off individuals. Their "genetic makeup" is still being used to create offsprings, so they can still generate new, more fit individuals. 

I understand that for some use cases that behaviour might not be wanted, so there could be an option to deactivate that behaviour, if so desired. The default behaviour would still be the one currently implemented. 

Please feel free to implement this behaviour as a user defined option, and also add that to the README. 

Thanks!
