### ISSUE TITLE
Improve initialize_population method for binary optimization

### ISSUE THREAD

**Issue by mikeliux** [diogomatoschaves/geneal#2]
The current` initialize_population` method for binary optimization is:
```
    def initialize_population(self):
        """
        Initializes the population of the problem according to the
        population size and number of genes and outputs individuals
        composed of 0's and 1's.

        :return: a numpy array with a randomized initialized population
        """             
        return np.round(np.random.rand(self.pop_size, self.n_genes))
```
Since each gene in the chromosome will have a 50% chance of being 0 or 1, this method yields chromosomes which will most likely have 50% 0's and 1's. This is similar to tossing a coin N times. As a result, it will be unlikely that it generates chromosome that is mostly made of 0's or mostly made of 1's, thus limiting the population diversity.

I suggest the use of a different method for each individual:
1. Generate a uniformly distributed random integer between 0 and n_genes for each individual, which will be the number of ones in the chromosome.
2. Create a vector of exactly with exactly this number of 1's, filling the rest with 0's. This vector is then shuffled randomly.

Below is a sample code:
```
import random
    def initialize_population(self):
        """
        Initializes the population of the problem according to the
        population size and number of genes and outputs individuals
        composed of 0's and 1's.

        :return: a numpy array with a randomized initialized population
        """          
        bitArray = []
         
        for k in range(self.pop_size):            
            number_of_ones = random.randint(0,self.n_genes)
            rbits = [0]*(self.n_genes-number_of_ones) + [1]*number_of_ones            
            random.shuffle(rbits)
            bitArray.append(rbits)  
      
        return np.array(bitArray)
```

**Comment by diogomatoschaves** [comment]
That's a fair point! It's true that the way it is implemented now the initialised population lacks diversity. 

I'll implement this change and I'll let you know.

**Comment by diogomatoschaves** [comment]
That's the commit with the changes: https://github.com/diogomatoschaves/geneal/commit/df92be7addca71983a25bef8607b9acf0a37056e

I'll close this issue.
