### ISSUE TITLE
variable limit is exceeded on crossover point

### ISSUE THREAD

**Issue by Loridan** [diogomatoschaves/geneal#5]
the rule of calculation during a parent crossing has been implemented without taking into account the limits of the variables.

I simply added a rule not to exceed on the crossing point (if problem_type not float) in _continious.create_offspring() :

```
variable_limits = self.variables_limits[crossover_pt]
if not variable_limits[0] <= p_new <= variable_limits[1] :
    p_new = np.random.randint(variable_limits[0], variable_limits[1] + 1)
```

**Comment by diogomatoschaves** [comment]
Hi Adrien, thanks for your input 👌

You are right, that assertion should be there. Can you implement that change and open a pull request?

Thanks!

**Comment by SiddhiMali** [comment]
Hii!
Is the issue resolved ?

**Comment by diogomatoschaves** [comment]
@SiddhiMali It is.
