### ISSUE TITLE
Can we stop iteration if the best fitness value doesn't improve after a few iterations?

### ISSUE THREAD

**Issue by hyperkang** [diogomatoschaves/geneal#6]
I run some tests, it works pretty well.  Thanks for the great work!

However I find that even if the max fitness value doesn't improve after a few iterations, it would not stop until it runs out of max_gen. This might cause unnecessary calls to fitness_function, which could be quite expensive in some applications.

**Comment by diogomatoschaves** [comment]
@hyperkang Took a while, but it's done!
