### ISSUE TITLE
How do I use a custom fitness function

### ISSUE THREAD

**Issue by pranavn91** [diogomatoschaves/geneal#7]
Can you add an example so that I can resolve my query
https://stackoverflow.com/questions/69381860/gene-ai-package-python-define-a-custom-fitness-function

**Comment by diogomatoschaves** [comment]
A fitness function has 2 requirements:

- It must get passed one and only one argument - the chromossome. The chromossome is an numpy array of 1's and 0's if it's the binary genetic algorithm solver, or an numpy array of numbers between 0 and 9 if it's the continuous genetic algorithm solver. The size of this array is defined by the number of genes you initialize the solver with, and each position on the array corresponds to a different variable. 

- It must return a real number.

The inner workings of this function are up for you to decide.

I suggest you look at the examples provided in the package to get a better idea of how to define a custom fitness function: [examples](https://github.com/diogomatoschaves/geneal/blob/master/geneal/applications/fitness_functions/continuous.py)
