### ISSUE TITLE
Thesis

### ISSUE THREAD

**Issue by ckattenberg** [diogomatoschaves/geneal#9]
Hi there. I would like to use this package for my Bachelor's Thesis. Would that be okay? If so, how would you like me to reference the package?

**Comment by diogomatoschaves** [comment]
Hey 👋. Yeah you can use it of course! Just follow any of the citation recommendations you have in this 
[page](https://www.wikihow.com/Cite-a-GitHub-Repository) for example. Good luck ✌️
